export const INITIAL_FETCH = "INITIAL_FETCH";
export const GENERATE_MEMORY = "GENERATE_MEMORY";
export const UPDATE_MEMORY = "UPDATE_MEMORY";
export const DEPOSIT_MEMORY = "DEPOSIT_MEMORY";
export const UPDATE_PAST_FUTURE = "UPDATE_PAST_FUTURE";